### ISSUE TITLE
Get TypeError: Class constructor MicroserviceClient cannot be invoked without 'new'

### ISSUE THREAD

**Issue by WadeMerlix** [fuzzy-io/nodejs#6]
I am trying to run the tutorial NodeJS code (running v8.11.1) and I am getting this error: "TypeError: Class constructor MicroserviceClient cannot be invoked without 'new'" Here is the code I am trying to run:

var FuzzyAIClient = require('fuzzy.ai');

var API_KEY = 'xxxxxxxxxxxx';
var AGENT_ID = 'xxxxxxxxxxxx';

var client = new FuzzyAIClient({ key: API_KEY});

client.evaluate(AGENT_ID, {Temperature: 90}, function(err, outputs) {
  if (err) {
    console.error(err);
  } else {
    console.log(outputs['price per cup']);
  }
});

Thanks.

Wade

**Comment by evanp** [comment]
Did you install from npm or from GitHub?

**Comment by growthlabs** [comment]
@evanp I'm experiencing the same error. I tried installing from the github repo but also from NPM but with the same result. So I suspect it may have something to do with the node version. This is my version: v8.7.0 

I've also tried using the following LTS versions via NVM:  
6.14.3 
8.9.0

I still get the same error however:

```
/Users/paolo/Coding/fuzzyai/nodejs/lib/fuzzy.ai.js:52
      FuzzyAIClient.__super__.constructor.call(this, props);
                                          ^

TypeError: Class constructor MicroserviceClient cannot be invoked without 'new'
    at new FuzzyAIClient (/Users/paolo/Coding/fuzzyai/nodejs/lib/fuzzy.ai.js:52:43)
    at Object.<anonymous> (/Users/paolo/Coding/fuzzyai/app.js:6:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Also, lastly when I run a test I get this error:
```
···✗✗✗✗✗✗✗✗✗✗✗✗✗✗✗✗✗✗✗✗✗✗✗ 
   
  ✗ Errored » Asynchronous Error 
      in Basic fuzzy.ai test 
      in test/module-test.js✗ Errored » 3 honored ∙ 2 broken ∙ 22 errored
```

**Comment by evanp** [comment]
OK, I'll see if I can replicate. Thanks for the report! Should have something pushed to npm and GitHub in ~24h

**Comment by evanp** [comment]
OK, I see what the problem was. I think we're testing correctly on NodeJS 6, 8, and 10. Travis CI is showing all green across those versions, so I think you should be ready to go. Can you confirm?

**Comment by evanp** [comment]
Oh, and it's been published to npm, also. So, should be all good.

**Comment by WadeMerlix** [comment]
Excellent, that worked!
